language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g bower grunt-cli protractor
  # - webdriver-manager update
install:
  - npm install
script:
  - grunt test:development
  - grunt test
  # - nohup webdriver-manager start &
  # - grunt e2e --ci
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
# addons:
#   sauce_connect: true
